### ISSUE TITLE
ru_summarise_fq error

### ISSUE THREAD

**Issue by svennd** [LooseLab/ru#20]
I'm trying to reproduce the tests described in the readme, when I received this error : 
```ru_summarise_fq human_chr_selection.toml /data/gpubase/gpubase/20200225_1318_MN23294__1af2ac4f/fastq/
Using reference: /data/minimap2.mmi
Traceback (most recent call last):
  File "/home/minion/read_until/bin/ru_summarise_fq", line 11, in <module>
    load_entry_point('ru==2.0.0', 'console_scripts', 'ru_summarise_fq')()
  File "/home/minion/read_until/lib/python3.6/site-packages/ru/summarise_fq.py", line 125, in main
    "{:.0f}".format(stdev(data)),
  File "/usr/lib/python3.6/statistics.py", line 650, in stdev
    var = variance(data, xbar)
  File "/usr/lib/python3.6/statistics.py", line 588, in variance
    raise StatisticsError('variance requires at least two data points')
```

I used the [demo file](https://github.com/LooseLab/ru/blob/master/examples/human_chr_selection.toml) and changed chr22 to chr15;

The experiment ran on a minion, connected to a computer with a GPU (2080 ti) so minknow, did not basecall directly (as this would work on CPU).

I had the "feeling" reads where beeing pushed out correctly and the basecall_server running GPU and connected to the RU was working; However I never installed minimap2 so I'm unsure how the ru knows if it maps in a correct region ? 

After the test (~15min) I basecalled using the same GPU basecall_server (v3.4.4) and ran the above command; Did I forget a step ? the fastq's are 7,3mb, 13mb, 30mb, 32mb. So i guess they contain some thing ?

Thanks for this nice pioneering work :)

**Comment by alexomics** [comment]
This error suggests that there was only one read for a given contig in your dataset. How many reads are in the basecalled FASTQ?

**Comment by svennd** [comment]
16000 fastq_runid_f486f3152508158c258bf4074f0474de50e28c3a_0_0.fastq
    16000 fastq_runid_f486f3152508158c258bf4074f0474de50e28c3a_1_0.fastq
    16000 fastq_runid_f486f3152508158c258bf4074f0474de50e28c3a_2_0.fastq
    16000 fastq_runid_f486f3152508158c258bf4074f0474de50e28c3a_3_0.fastq
     6888 fastq_runid_f486f3152508158c258bf4074f0474de50e28c3a_4_0.fastq

**Comment by alexomics** [comment]
That's a bit odd, can you map the reads with minimap2 and then run this command:

```bash
minimap2 -x map-ont <REF.mmi> *.fastq > mappings.paf
cut -f6 mappings.paf | sort | uniq -c
``` 

and put the output here?

**Comment by svennd** [comment]
w/ minimap2 : 2.17-r974-dirty
./minimap2/minimap2 -x map-ont ru/minimap2.mmi ru/*.fastq

```  1894 chr1
    971 chr10
   1062 chr11
   1018 chr12
    798 chr13
    639 chr14
      3 chr14_GL000009v2_random
      2 chr14_GL000194v1_random
      2 chr14_GL000225v1_random
      5 chr14_KI270722v1_random
      1 chr14_KI270725v1_random
    108 chr15
      1 chr15_KI270727v1_random
    558 chr16
     31 chr16_KI270728v1_random
    610 chr17
      5 chr17_KI270729v1_random
      2 chr17_KI270730v1_random
    623 chr18
    644 chr19
      2 chr1_KI270706v1_random
      6 chr1_KI270708v1_random
    228 chr1_KI270709v1_random
   1886 chr2
    641 chr20
     58 chr21
    247 chr22
      6 chr22_KI270733v1_random
      1 chr22_KI270735v1_random
      3 chr22_KI270736v1_random
      1 chr2_KI270716v1_random
   1150 chr3
   1326 chr4
   1317 chr5
      1 chr5_GL000208v1_random
   1086 chr6
   1088 chr7
    916 chr8
   1393 chr9
     13 chr9_KI270719v1_random
      1 chr9_KI270720v1_random
     24 chrEBV
    147 chrM
     11 chrUn_GL000216v2
      3 chrUn_GL000219v1
      5 chrUn_GL000220v1
      3 chrUn_GL000224v1
     25 chrUn_GL000226v1
     52 chrUn_KI270333v1
      7 chrUn_KI270336v1
      8 chrUn_KI270337v1
      1 chrUn_KI270382v1
      1 chrUn_KI270393v1
      1 chrUn_KI270395v1
      2 chrUn_KI270419v1
      1 chrUn_KI270435v1
     59 chrUn_KI270438v1
      3 chrUn_KI270442v1
      1 chrUn_KI270448v1
     16 chrUn_KI270466v1
     64 chrUn_KI270467v1
      1 chrUn_KI270519v1
      2 chrUn_KI270521v1
      1 chrUn_KI270579v1
      1 chrUn_KI270580v1
      1 chrUn_KI270581v1
      1 chrUn_KI270747v1
      2 chrUn_KI270749v1
      6 chrUn_KI270756v1
   1163 chrX
     77 chrY
```

**Comment by alexomics** [comment]
So the issue here is that there are single mappings to some contigs. 

Could you uninstall ru and reinstall a test branch?
```bash
pip uninstall ru
pip install git+https://github.com/LooseLab/ru@summarise_patch
```
Then test the script again?

**Comment by svennd** [comment]
I tested on the test branch this does fix it : 
```
Skipping contig chr9_KI270719v1_random, too few mappings
Skipping contig chrUn_GL000220v1, too few mappings
Skipping contig chrUn_KI270519v1, too few mappings
Skipping contig chrUn_KI270521v1, too few mappings
Skipping contig chrUn_KI270580v1, too few mappings
Skipping contig chrUn_KI270747v1, too few mappings
Skipping contig chrUn_KI270756v1, too few mappings
                 contig  number      sum   min     max    std   mean  median    N50
                   chr1    1318  3758694   227  312587  15213   2852     646  72153
                  chr10     797  2364155   253  225658  14992   2966     657  58338
                  chr11     846  2410369   193  283646  15071   2849     658  55785
                  chr12     957  2083884   220  116602   9357   2178     641  41484
                  chr13     477  1132216   227  140920  11668   2374     625  49985
                  chr14     601  2173813   223  198938  17228   3617     671  93731
chr14_GL000009v2_random       2    31600   503   31097  21633  15800   15800  31097
                  chr15      67  2030911   272  142887  38601  30312   11162  78080
                  chr16     477  1431626   242  151940  13091   3001     647  53137
chr16_KI270728v1_random       5     3476   590    1012    179    695     618    618
                  chr17     470  1475990   226  307905  18960   3140     644  91748
                  chr18     457  1259391   252  246156  14449   2756     643  53857
                  chr19     609  1650271   209  179717  13108   2710     620  63874
 chr1_KI270708v1_random       6     2976   300     605    125    496     542    556
 chr1_KI270709v1_random      45    44306   477    6462    910    985     863   1013
                   chr2    1505  3800414   224  201737  12732   2525     638  49108
                  chr20     435  1839035   229  227281  19278   4228     636  82913
                  chr21      22   742632   365  207508  52381  33756   10885  83805
                  chr22     167   359779   244   48439   6078   2154     679  14483
chr22_KI270733v1_random       2    29648  5056   24592  13814  14824   14824  24592
                   chr3    1004  3135923   167  205187  15877   3123     620  73300
                   chr4    1022  3831506   197  201886  16954   3749     654  66044
                   chr5    1093  3958125   213  301364  18186   3621     645  94407
                   chr6     967  2342620   238  139892  10610   2423     637  36401
                   chr7     966  2644245   202  212324  14698   2737     645  55037
                   chr8     752  2358638   242  255258  17977   3136     634  57974
                   chr9     895  2797407   190  226041  14654   3126     633  54344
                 chrEBV      24    21089   306    1882    314    879     868    908
                   chrM     134   214547   381   28384   3463   1601     688   4838
       chrUn_GL000216v2       3    27053   553   25465  14246   9018    1035  25465
       chrUn_GL000226v1       6    11597   627    8335   3137   1933     646   8335
       chrUn_KI270333v1       7     5844   670    1116    194    835     754    773
       chrUn_KI270438v1      25    49199   502   27076   5250   1968     753  27076
       chrUn_KI270466v1       2     1169   557     612     39    584     584    612
       chrUn_KI270467v1      12    54612   564   44220  12512   4551     646  44220
       chrUn_KI270749v1       3    17951   514   16857   9417   5984     580  16857
                   chrX    1054  2836546   238  183490  13215   2691     645  52681
```
Seems it worked, I selected chr15 & chr21;

**Comment by alexomics** [comment]
Nice! I'll merge this in!
